spring.application.name=Online-Food-Ordering
server.port=8080

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://user@localhost:3306/db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
